services:
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    volumes:
      - ./code:/data/mysite.local
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
